Repository ifpeopensource/ifpeopensource.com.br, pull requests merged in 2021-04, with the labels that each got.

#9 Removes privacy policy
  src/components/Footer/index.tsx
Labels: bug

#11 Atualiza as dependências do projeto para o mais recente
  package.json
  yarn.lock
Labels: dependencies

#12 Adiciona o projeto "StockID"
  projects.json
Labels: enhancement

#10 Atualiza o conteúdo dos textos
  src/components/HeroHeader/index.tsx
  src/components/HowToJoin/index.tsx
  src/components/Projects/index.tsx
  src/components/WhoWeAre/ReadMoreModal/index.tsx
  src/components/WhoWeAre/index.tsx
Labels: enhancement

#13 Adicionar ícone do Instagram ao rodapé
  src/components/Footer/index.tsx
Labels: enhancement

#14 Evitar saída não intencional pelos links de mídias sociais
  src/components/Footer/SocialButton/index.tsx
Labels: enhancement

#16 Atualiza imagem do projeto
  projectImage.jpg
Labels: enhancement

#15 Atualizar o README do projeto
  README.md
Labels: documentation

#17 Corrigir erros gramaticais
  src/components/Projects/index.tsx
  src/components/WhoWeAre/ReadMoreModal/index.tsx
  src/components/WhoWeAre/index.tsx
Labels: bug

#18 Atualizar meta tags
  src/pages/_document.tsx
Labels: bug

#19 Atualizar sitemap
  public/sitemap.xml
Labels: bug

#20 feat: Banner StockID e keywords
  projects.json
Labels: enhancement

#22 Atualizar nome deste repositório na lista de projetos
  projects.json
Labels: enhancement
